export enum DatabaseConstraints {
  // ROUTE
  ROUTE_PKEY = 'ROUTE_PKEY',
  ROUTE_NAME_UNIQUE = 'ROUTE_NAME_UNIQUE',

  // WAYPOINT
  WAYPOINT_PKEY = 'WAYPOINT_PKEY',
  WAYPOINT_NAME_UNIQUE = 'WAYPOINT_NAME_UNIQUE',

  // EXPEDITION
  EXPEDITION_PKEY = 'EXPEDITION_PKEY',
  EXPEDITION_NAME_UNIQUE = 'EXPEDITION_NAME_UNIQUE',

  // EXPEDITION-WAYPOINT
  EXPEDITION_WAYPOINT_PKEY = 'EXPEDITION_WAYPOINT_PKEY',
  EXPEDITION_WAYPOINT_EXPEDITION_ID_FKEY = 'EXPEDITION_WAYPOINT_EXPEDITION_ID_FKEY',
  EXPEDITION_WAYPOINT_WAYPOINT_ID_FKEY = 'EXPEDITION_WAYPOINT_WAYPOINT_ID_FKEY',

  // EXPEDITION-ROUTE
  EXPEDITION_ROUTE_PKEY = 'EXPEDITION_ROUTE_PKEY',
  EXPEDITION_ROUTE_EXPEDITION_ID_FKEY = 'EXPEDITION_ROUTE_EXPEDITION_ID_FKEY',
  EXPEDITION_ROUTE_ROUTE_ID_FKEY = 'EXPEDITION_ROUTE_ROUTE_ID_FKEY',

  // SKILL-CATEGORY
  SKILL_CATEGORY_PKEY = 'SKILL_CATEGORY_PKEY',

  // SKILL
  SKILL_PKEY = 'SKILL_PKEY',
  SKILL_CATEGORY_ID_FKEY = 'SKILL_CATEGORY_ID_FKEY',

  // SKILL-LEVEL
  SKILL_LEVEL_PKEY = 'SKILL_LEVEL_PKEY',
  SKILL_LEVEL_SKILL_ID_FKEY = 'SKILL_LEVEL_SKILL_ID_FKEY',
  SKILL_LEVEL_SKILL_ID_LEVEL_UNIQUE = 'SKILL_LEVEL_SKILL_ID_LEVEL_UNIQUE',
}
