export enum ErrorCodes {
  // SERVER ERROR
  SERVER_ERROR = 'SERVER_ERROR',

  // BAD REQUEST
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  DUPLICATE_ASSESSMENT = 'DUPLICATE_ASSESSMENT',
  METEOBLUE_API_ERROR = 'METEOBLUE_API_ERROR',
  OPEN_WEATHER_API_ERROR = 'OPEN_WEATHER_API_ERROR',
  INVALID_MIME_TYPE = 'INVALID_MIME_TYPE',
  INVALID_IMAGE_DIMENSIONS = 'INVALID_IMAGE_DIMENSIONS',
  INVALID_IMAGE_SIZE = 'INVALID_IMAGE_SIZE',

  // UNAUTHORIZED ERROR
  INVALID_API_ADMIN_TOKEN = 'INVALID_API_ADMIN_TOKEN',
  INVALID_DERSU_ADMIN_CREDENTIALS = 'INVALID_DERSU_ADMIN_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // NOT FOUND ERROR
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  WAYPOINT_NOT_FOUND = 'WAYPOINT_NOT_FOUND',
  EXPEDITION_NOT_FOUND = 'EXPEDITION_NOT_FOUND',
  SKILL_CATEGORY_NOT_FOUND = 'SKILL_CATEGORY_NOT_FOUND',
  SKILL_NOT_FOUND = 'SKILL_NOT_FOUND',
  SKILL_LEVEL_NOT_FOUND = 'SKILL_LEVEL_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WAYPOINT_TYPE_NOT_FOUND = 'WAYPOINT_TYPE_NOT_FOUND',
  ACTIVITY_TYPE_NOT_FOUND = 'ACTIVITY_TYPE_NOT_FOUND',
}
