version: "3.8"
services:
  api:
    build:
      context: ./api2
      target: builder
    depends_on:
      - database
    ports:
      - "3033:3033"
    volumes:
      - ./api2/src:/home/dersu-api/src
      - ./api2/.env:/home/dersu-api/secrets/.env
      - $GOOGLE_APPLICATION_CREDENTIALS:/home/dersu-api/sa.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/dersu-api/sa.json
  database:
    image: postgis/postgis:13-3.1
    shm_size: 256MB
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dersu-user
      POSTGRES_DB: dersu-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
  admin-console:
    build:
      context: ./admin-console
      target: builder
      args:
        NODE_ENV: local
        REACT_APP_ENV: local
        REACT_APP_API_BASE_URL: http://localhost:3033
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
      REACT_APP_ENV: local
      REACT_APP_API_BASE_URL: http://localhost:3033
    volumes:
      - ./admin-console/src:/home/dersu-admin-console/src
