version: "3.8"
services:
  api:
    build: ./api2
    command: npm run start:dev
    ports:
      - "3033:3033"
    environment:
      APP_PORT: 3033
      APP_URL: "http://localhost:3033"
      NODE_ENV: "local"
      DB_HOST: "database"
      DB_USER: "dersu-user"
      DB_PASSWORD: "123456"
      DB_DATABASE: "dersu-db"
      API_ADMIN_TOKEN: "123456"
      AUTH0_ISSUER_URL: "https://dersu-develop.eu.auth0.com/"
      AUTH0_AUDIENCE: dersu-develop
      AUTH0_TENANT: "dersu-develop.eu"
      AUTH0_CLIENT_ID: "lRSRyxGj1gKcYRKq7tC3IltEWz6CSdUD"
      AUTH0_CLIENT_SECRET:
    volumes:
      - ./api2/src:/home/dersu-api/src
  database:
    image: mdillon/postgis:11-alpine
    shm_size: 256MB
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dersu-user
      POSTGRES_DB: dersu-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
  admin-console:
    build:
      context: ./admin-console
      target: builder
      args:
        NODE_ENV: local
        REACT_APP_ENV: local
        REACT_APP_API_BASE_URL: http://localhost:3033
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
      REACT_APP_ENV: local
      REACT_APP_API_BASE_URL: http://localhost:3033
    volumes:
      - ./admin-console/src:/home/dersu-admin-console/src
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
