include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    avoid_print: false
    overridden_fields: false

analyzer:
  exclude:
    - lib/generated/locale_keys.g.dart
    - dersu_permissions