name: app

publish_to: "none"

version: 1.1.2+63

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 7.2.1
  connectivity: 3.0.6
  cupertino_icons: 1.0.4
  dio: 4.0.1
  either_option: 2.0.0
  equatable: 2.0.3
  flutter_background_geolocation: 4.3.0
  flutter_bloc: 7.3.3
  flutter_local_notifications: 9.0.3
  get_it: 7.2.0
  hive: 2.0.4
  hive_flutter: 1.1.0
  intl: 0.17.0
  ionicons: 0.1.2
  json_annotation: 4.3.0
  package_info: 2.0.2
  path_provider: 2.0.6
  pretty_dio_logger: 1.2.0-beta-1
  share_plus: 3.0.4
  shared_preferences: 2.0.8
  unicons: 2.0.2
  url_launcher: 6.0.12
  flutter_config: 2.0.0
  easy_localization: 3.0.0
  modal_bottom_sheet: 2.0.0
  flutter_appauth: 1.1.0+2
  flutter_secure_storage: 4.2.1
  cubit_form: 1.0.19-nullsafety.0
  device_info_plus: 3.1.1
  flutter_map: 0.14.0
  animations: 2.0.2
  cached_network_image: 3.1.0+1
  linked_scroll_controller: 0.2.0
  image_picker: 0.8.4+4
  permission_handler: 8.2.6
  image_cropper: 1.4.1
  overlay_support: 1.2.1
  dersu_permissions:
    path: dersu_permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  build_runner: 2.1.5
  hive_generator: 1.1.1
  json_serializable: 6.0.1
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 1.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/app_icon/android-1024x1024.png"
  image_path_ios: "assets/app_icon/ios-1024x1024.png"

flutter_native_splash:
  background_image: "assets/splash_screen/background.png"
  image: "assets/splash_screen/logo.png"
  android_gravity: bottom|left
  ios_content_mode: bottomLeft
  web: false
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - distribution/whatsnew/whatsnew-es-ES
    - assets/translations/
    - assets/weather_pictos/

  fonts:
    - family: DersuIcons
      fonts:
        - asset: assets/fonts/DersuIcons.ttf
