name: app

publish_to: "none"

version: 1.1.0+47

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: 7.2.0
  connectivity: 3.0.6
  cupertino_icons: 1.0.2
  dio: 4.0.0
  either_option: 2.0.0
  equatable: 2.0.3
  flutter_background_geolocation: 4.0.2
  flutter_bloc: 7.3.0
  flutter_local_notifications: 6.0.0
  get_it: 7.1.3
  google_maps_flutter: 2.0.8
  hive: 2.0.4
  hive_flutter: 1.1.0
  intl: 0.17.0
  ionicons: 0.1.2
  json_annotation: 4.0.1
  notification_permissions: 0.5.0
  package_info: 2.0.0
  path_provider: 2.0.2
  pretty_dio_logger: 1.2.0-beta-1
  share_plus: 2.1.4
  shared_preferences: 2.0.6
  unicons: 2.0.1
  url_launcher: 6.0.4
  flutter_config: 2.0.0
  easy_localization: 3.0.0
  modal_bottom_sheet: 2.0.0
  flutter_appauth: 1.1.0
  flutter_secure_storage: 4.2.1
  cubit_form: 1.0.19-nullsafety.0
  device_info_plus: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.2
  hive_generator: 1.1.0
  json_serializable: 4.1.3

flutter:
  uses-material-design: true
  assets:
    - distribution/whatsnew/whatsnew-es-ES
    - assets/translations/
