name: app

publish_to: 'none'

version: 1.0.0+27

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  either_option: ^1.0.6
  equatable: ^2.0.3
  flutter_background_geolocation: ^4.0.2
  flutter_bloc: ^7.0.1
  flutter_dotenv: ^5.0.0
  flutter_local_notifications: ^6.0.0
  get_it: ^7.1.3
  google_maps_flutter: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  notification_permissions: ^0.5.0
  package_info: ^2.0.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.6
  unicons: ^2.0.1
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  hive_generator: ^1.1.0
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - develop-public.env
    - distribution/whatsnew/whatsnew-es-ES
