name: Android build
on:
  push:
    branches:
      - "develop"
    paths:
      - "app/**"
      - ".github/workflows/android.yml"
      - ".github/workflows/android-test.yml"
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Write JKS file for signing
        run: echo $ANDROID_JKS > key.b64 && base64 -d key.b64 > $ANDROID_JKS_PATH
        env:
          ANDROID_JKS: ${{ secrets.ANDROID_JKS }}
          ANDROID_JKS_PATH: "${{ github.workspace }}/android-key.jks"
      - name: Get Flutter dependencies
        working-directory: app
        run: flutter pub get
      - name: Test
        working-directory: app
        run: flutter test
      - name: Build app bundle
        working-directory: app
        run: |
          touch .env
          echo ANDROID_MAPS_API_KEY=${{ secrets.ANDROID_MAPS_API_KEY }} >> .env
          echo IOS_MAPS_API_KEY=${{ secrets.IOS_MAPS_API_KEY }} >> .env
          echo TRANSISTOR_BG_LOCATOR_KEY=${{ secrets.TRANSISTOR_BG_LOCATOR_KEY }} >> .env
          echo DERSU_API_BASE_URL=https://develop-api.dersu.uz/personal >> .env
          echo DERSU_SITE_BASE_URL=https://dersu.uz >> .env
          echo API_TEMP_KEY=${{ secrets.API_ADMIN_TOKEN_DEVELOP }} >> .env
          echo ANDROID_JKS_PATH=${{ github.workspace }}/android-key.jks>> .env
          echo ANDROID_STORE_PASSWORD=${{ secrets.ANDROID_STORE_PASSWORD }} >> .env
          echo ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }} >> .env
          echo ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }} >> .env
          echo PLAUSIBLE_URL=us.dersu.assistant.pilot.develop >> .env
          flutter build appbundle
      - name: Generate What Is New Files
        run: echo $GITHUB_SHA >> app/distribution/whatsnew/whatsnew-es-ES && cat app/distribution/whatsnew/whatsnew-es-ES
      - name: Write SA KEY file
        run: echo $GCP_SA_KEY > ./sa-key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ./sa-key.json
          packageName: uz.dersu.assistant.pilot
          releaseFiles: ${{ github.workspace }}/app/build/app/outputs/bundle/release/*.aab
          track: alpha
          inAppUpdatePriority: 0
          # userFraction: 1.0
          whatsNewDirectory: app/distribution/whatsnew
