name: API test
on:
  push:
    paths:
      - "services/api2/**"
      - ".github/workflows/api-test.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: services/api2
          useRollingCache: false
      - name: Lint
        working-directory: services/api2
        run: echo "I NEED TESTS"
