# FROM:
# https://github.com/docker/build-push-action

name: Build, push and deploy Dersu API
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'services/api/**'
      - 'services/terraform/**'
      - '.github/workflows/api.yml'      
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Short commit SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Check out
        uses: actions/checkout@v2        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          export_default_credentials: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker --quiet
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: services/api
          push: true
          tags: gcr.io/dersu-assistant/api:${{ steps.slug.outputs.sha8 }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10
      - name: Terraform init
        working-directory: services/terraform
        run: terraform init -input=false -lock=true 
      - name: Terraform plan
        working-directory: services/terraform
        run: |
          terraform plan -input=false -lock=true -out=tfplan \
          -var="dersu_api_docker_image_tag=${{ steps.slug.outputs.sha8 }}"
      - name: Terraform apply
        working-directory: services/terraform
        run: terraform apply -input=false -lock=true tfplan
          

